# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
a1

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])
a2
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,111,12],[13,14,15],[16,17,18]]])
a3

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10, 111,  12],
        [ 13,  14,  15],
        [ 16,  17,  18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a1.shape,type(a1)

((3,), numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array


In [6]:
# Attributes of 3-dimensional array


In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
frame = pd.DataFrame(a2,index=["haha","hehe"],columns=["oooo","aaa","eeee"])
frame

,oooo,aaa,eeee
haha,1,2,3
hehe,4,5,6


In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros((7,2,3) , dtype = np.int64)
zeroes

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
rand = np.arange(0,100,3)
rand


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand1 = np.random.randint(0,10, size = (7,2))
rand1

array([[8, 6],
       [3, 8],
       [1, 8],
       [5, 6],
       [8, 1],
       [5, 8],
       [9, 5]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)rand
rand2 = np.random.random((3,5))
rand2

array([[0.87755628, 0.67889251, 0.51811487, 0.06974071, 0.80216852],
       [0.9257868 , 0.51949401, 0.82999971, 0.40246485, 0.9880334 ],
       [0.10194131, 0.29340587, 0.28941682, 0.5848163 , 0.35148141]])

In [52]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand3 = np.random.randint(0,10,size =(4,6) )
rand3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [54]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand4 = np.random.randint(0,10, size = (3,7) )
rand4
# Find the unique numbers in the array you just created
np.unique(rand4)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [55]:
rand4

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5],
       [9, 3, 5, 1, 9, 1, 9]])

In [57]:
# Find the 0'th index of the latest array you created
rand4[0]
rand4[0,0]

4

In [58]:
# Get the first 2 rows of latest array you created
rand4[:2]

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5]])

In [59]:
# Get the first 2 values of the first 2 rows of the latest array
rand4[:2,:2]

array([[4, 1],
       [3, 1]])

In [60]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand5 = np.random.randint(0,10, size = (3,5))
rand6 =np.ones((3,5))


In [61]:
rand5


array([[3, 7, 6, 8, 7],
       [4, 1, 4, 7, 9],
       [8, 8, 0, 8, 6]])

In [62]:
rand6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
# Add the two arrays together
rand5+rand6

array([[ 4.,  8.,  7.,  9.,  8.],
       [ 5.,  2.,  5.,  8., 10.],
       [ 9.,  9.,  1.,  9.,  7.]])

In [65]:
# Create another array of ones of shape (5, 3)
rand7 = np.ones((5,3))
rand7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
# Try add the array of ones and the other most recent array together
rand6+rand7

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)


In [23]:
# Subtract the new array of ones from the other most recent array


In [24]:
# Multiply the ones array with the latest array


In [25]:
# Take the latest array to the power of 2 using '**'


In [26]:
# Do the same thing with np.square()


In [27]:
# Find the mean of the latest array using np.mean()


In [28]:
# Find the maximum of the latest array using np.max()


In [29]:
# Find the minimum of the latest array using np.min()


In [30]:
# Find the standard deviation of the latest array


In [31]:
# Find the variance of the latest array


In [32]:
# Reshape the latest array to (3, 5, 1)


In [33]:
# Transpose the latest array


What does the transpose do?

In [34]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [35]:
# Perform a dot product on the two newest arrays you created


In [36]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [37]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [38]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [39]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [40]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [41]:
# Compare the two arrays with '>='


In [42]:
# Find which elements of the first array are greater than 7


In [43]:
# Which parts of each array are equal? (try using '==')


In [44]:
# Sort one of the arrays you just created in ascending order


In [45]:
# Sort the indexes of one of the arrays you just created


In [46]:
# Find the index with the maximum value in one of the arrays you've created


In [47]:
# Find the index with the minimum value in one of the arrays you've created


In [48]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [49]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [50]:
# Create an array of normally distributed random numbers


In [51]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.